import { getSession } from 'next-auth/react'
import Head from 'next/head'
import Header from '../components/Header'



export default function Home() {
  return (
    <div >
      <Head>
        <title>Black facebook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>
       <main>
         {/* sidebar */}
         {/* feed */}
         {/* wigdet */}
       </main>
    </div>
  )
  export async function getServerSideProps(context){
    //getting the user klogged import 'first'
    const session = await getSession(context);
     return{
       props:{
         session
       }
     }
  }
}

